apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: desafio-kubernetes
type: Opaque
stringData:
  postgres-username: postgres
  postgres-password: super-senha-segura
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: desafio-kubernetes
data:
  POSTGRES_DB: appdb
